use crate::msgbuf::MsgBuf;
use crate::type_alias::*;

pub(crate) struct SSlot {
    /// Current request index.
    pub req_idx: ReqIdx,

    /// Pre-allocated MsgBuf for single-packet responses.
    pre_resp_msgbuf: MsgBuf,

    /// Request MsgBuf.
    /// - For server: this is the request from client.
    ///   It can be either a borrowed buffer from the transport (for zero-copy for small requests),
    ///   or a dynamically allocated buffer (for large requests).
    /// - For client: this is the user-provided request buffer.
    req: MsgBuf,

    /// Response MsgBuf.
    /// - For server: this is the response generated by the RPC handler.
    ///   No need for an `Option`, since burying a fake `MsgBuf` is an no-op.
    /// - For client: this is the user-provided response buffer.
    resp: MsgBuf,
}
